# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Mac arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v6

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'

    - name: Install Dependencies
      run: brew install --force mpv && brew install --force dylibbundler

    - name: Setup path
      run: export C_INCLUDE_PATH=/usr/local/include:/opt/homebrew/include:$C_INCLUDE_PATH && export LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:$LIBRARY_PATH

    - name: Install Fyne tool
      run: go install fyne.io/tools/cmd/fyne@latest

    - name: Package app bundles
      run: >
        make package_macos &&
        make bundledeps_macos_homebrew &&
        make zip_macos

    - name: Upload package
      uses: actions/upload-artifact@v6
      with:
        name: Supersonic.zip
        path: Supersonic.zip

